version: '3'
services:
  helium_integration_tester:
    build:
      context: .
      dockerfile: Dockerfile
    image: helium_integration_tester:local
    container_name: helium_integration_tester
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - prometheus
  prometheus:
      image: prom/prometheus
      container_name: helium_prometheus
      restart: always
      volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
