# my global config
global:
  scrape_interval: 10s
  external_labels:
    server: helium_integration_tester

scrape_configs:
  - job_name: helium_integration_tester
    static_configs:
      - targets: ['helium_integration_tester:80']