-define(METRIC_DEVICE_PACKETS, "hit_device_packets_counter").
-define(METRIC_DEVICE_PACKETS_STATS, "hit_device_packets_stats_gauge").
-define(METRIC_HOTSPOTS_PER_DEVICE, "hit_hotspots_per_device_gauge").
